version: '3'

services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    security_opt:
      - no-new-privileges:true
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # Define the network that should be used
      - "traefik.docker.network=proxy"
      # URL to reach this container
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`) || Host(`whoami.domain.local`)"
      # Activation of TLS
      - "traefik.http.routers.whoami.tls=true"
      # If port is different than 80, use the following service:
      # - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
    networks:
      - proxy
  nginx:
    image: "nginx:latest"
    container_name: nginx
    expose:
      - 8080
    environment:
      - NGINX_HOST=nginx.domain.local
      - NGINX_PORT=8080
    volumes:
      - ./nginx-config/static:/usr/share/nginx/html
      - ./nginx-config/logs:/var/log/nginx
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config/templates:/etc/nginx/templates
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nginx_static.rule=Host(`nginx.docker.localhost`) || Host(`nginx.domain.local`)"
      - "traefik.http.routers.nginx_static.tls=true"
      - "traefik.http.services.nginx_static.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
